name: Check Code Quality

#Trigger workflow on push to the main branch 
on:
  push: 
    branches:
      - main

jobs:
#Job 1: code quality check 
 code-quality-check:
   runs-on: ubuntu-latest

   steps: 
    - name: Checkout Repository
      uses: action/checkout@v3
    - name: Run Super Linter
      uses: github/super-linter@v5
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_BASH: true


#Job 2: Test and Print Variables 
 test-print-variables:
   runs-on: ubuntu-latest
   needs: code-quality-check
   steps:
    - name: Print GitHub Username and token
      env:
       USERNAME: ${{ secrets.USERNAME }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Username: $USERNAME"
        echo "GitHub Token: $GITHUB_TOKEN"


#Job 3: Build and List files 
 Build: 
  runs-on: ubuntu-latest
  needs: test-print-variables
  steps:
   - name: Checkout Repository
     uses: actions/checkout@v3
   - name: List All Files and Folders
     run: ls -la
   - name: Make the script executeable
     run: chmod +x math_operations.sh
   - name: Run a bash script
     run: ./math_operations.sh

